export const fortunes = [
  "you will find a hidden stash of snacks when you least expect it.",
  "beware of unexpected cowlicks.",
  "you will win a dance-off against a penguin.",
  "avoid wearing socks with sandals, unless you're trying to start a new fashion trend.",
  "your phone battery will never die at 1%.",
  "you will be crowned the king/queen of finding lost socks.",
  "you will always remember the punchline of every joke.",
  "beware of rogue squirrels plotting against you.",
  "you will never again stub your toe on furniture.",
  "you will become fluent in speaking baby gibberish.",
  "you'll discover the secret to perfectly fluffy pancakes.",
  "beware of clowns hiding in your closet.",
  "you will never spill coffee on your white shirt before an important meeting.",
  "you will never step on a lego brick again.",
  "you will become a master of parallel parking.",
  "you will win the lottery, but only in your dreams.",
  "beware of pigeons with an agenda.",
  "your karaoke rendition of 'bohemian rhapsody' will bring tears of joy to everyone who hears it.",
  "you will invent a new type of cheese that becomes a worldwide sensation.",
  "you will never have to wait in line at a mcdonalds drivethrough.",
  "you will always have the perfect comeback.",
  "you will become an expert at untangling knots.",
  "you will never accidentally bite your tongue while eating.",
  "you will befriend a talking cat.",
  "you will discover the cure for the common cold, but forget to write it down.",
  "you will become a master of interpretive dance.",
  "you will be reunited with your lost childhood stuffed animal.",
  "you will have the best hair day of your life when nobody important is around to see it.",
  "you will win a heated argument with a stubborn goat.",
  "you will discover a hidden talent for juggling flaming torches.",
  "you will become a renowned expert in obscure trivia.",
  "you will never again have to endure a soggy cereal experience.",
  "you will find a genie lamp, but the genie will be on vacation.",
  "you will become a connoisseur of fine socks.",
  "you will become the world's leading authority on bellybutton lint.",
  "you will befriend a mischievous leprechaun.",
  "you will successfully navigate through a maze of bureaucracy.",
  "you will become an honorary member of the secret society of ninja librarians.",
  "you will win an argument with a stubborn door.",
  "you will discover a hidden talent for speaking fluent whale.",
  "you will never again have a bad hair day.",
  "you will become a master of the air guitar.",
  "you will discover a portal to a parallel universe but decide it's too much hassle to explore.",
  "you will have a 100% success rate in predicting the weather, but only for locations you've never been to.",
  "you will discover a treasure map, but it will lead you to a pile of old socks.",
  "you will become a master of spontaneous puns.",
  "you will become a world-renowned expert in interpreting bird calls.",
  "you will develop the ability to communicate with houseplants.",
  "you will win a staring contest with a statue.",
  "you will find a secret compartment in your refrigerator filled with ice cream.",
  "you will become the go-to person for untangling headphone cords.",
  "you will discover a secret passage in your house, but it will only lead to the basement.",
  "you will become an expert at finding the perfect parking spot.",
  "you will befriend a time-traveling hamster.",
  "you will have a brief but memorable encounter with a ufo.",
  "you will become the world's leading authority on interpretive mime.",
  "you will never again experience a brain freeze.",
  "you will develop a sixth sense for finding loose change on the ground.",
  "you will win a heated debate with a stubborn refrigerator magnet.",
  "you will discover the meaning of life, but forget it immediately.",
  "you will become a master of the art of napkin folding.",
  "you will win a thumb war against a champion thumb wrestler.",
  "you will befriend a wise-cracking parrot.",
  "you will find a hidden compartment in your sofa filled with loose change.",
  "you will become a master of parallel universes, but only in your dreams.",
  "you will develop the ability to talk to inanimate objects.",
  "you will become an expert at finding four-leaf clovers.",
  "you will win a staring contest with a goldfish.",
  "you will discover a secret society of sock puppet enthusiasts.",
  "you will become a renowned expert in deciphering ancient hieroglyphics.",
  "you will find a hidden treasure map, but it will lead you to a pile of old newspapers.",
  "you will become a master of the art of folding fitted sheets.",
  "you will win a staring contest with a goldfish.",
  "you will discover a secret society of sock puppet enthusiasts.",
  "you will become a renowned expert in deciphering ancient hieroglyphics.",
  "you will find a hidden treasure map, but it will lead you to a pile of old newspapers.",
  "you will become a master of the art of folding fitted sheets.",
  "you will win a thumb war against a champion thumb wrestler.",
  "you will befriend a wise-cracking parrot.",
  "you will find a hidden compartment in your sofa filled with loose change.",
  "you will become a master of parallel universes, but only in your dreams.",
  "you will develop the ability to talk to inanimate objects.",
  "you will become an expert at finding four-leaf clovers.",
  "you will win a staring contest with a goldfish.",
  "you will discover a secret society of sock puppet enthusiasts.",
  "you will become a renowned expert in deciphering ancient hieroglyphics.",
  "you will find a hidden treasure map, but it will lead you to a pile of old newspapers.",
  "you will become a master of the art of folding fitted sheets.",
  "you will win a staring contest with a goldfish.",
  "you will discover a secret society of sock puppet enthusiasts.",
  "you will become a renowned expert in deciphering ancient hieroglyphics.",
  "you will find a hidden treasure map, but it will lead you to a pile of old newspapers.",
  "you will become a master of the art of folding fitted sheets.",
  "you will find happiness in unexpected places.",
  "good things come to those who wait.",
  "a journey of a thousand miles begins with a single step.",
  "fortune favors the brave.",
  "you will soon receive good news.",
  "your creativity will lead to success.",
  "the best is yet to come.",
  "your hard work will pay off.",
  "love is just around the corner.",
  "everything will work out in the end.",
  "trust your instincts; they will guide you well.",
  "you will make a new friend soon.",
  "fortune smiles upon you today.",
  "let go of your worries; they won't help you.",
  "today is a good day to try something new.",
  "an unexpected windfall is coming your way.",
  "good fortune will find you soon.",
  "you are stronger than you realize.",
  "a new opportunity will arise soon.",
  "embrace change; it will lead to growth.",
  "the universe has a plan for you.",
  "your kindness will be repaid tenfold.",
  "a pleasant surprise awaits you.",
  "trust in yourself; you have the power to succeed.",
  "your future is bright.",
  "listen to your heart; it knows the way.",
  "luck is on your side today.",
  "a positive attitude will bring you success.",
  "you will overcome any obstacles in your path.",
  "good things come to those who believe.",
  "your determination will lead to victory.",
  "you will find joy in the little things.",
  "fortune smiles upon the generous.",
  "believe in yourself, and anything is possible.",
  "a happy event is on the horizon.",
  "your efforts will be rewarded.",
  "you are on the right path.",
  "love will find you when you least expect it.",
  "success is within your reach.",
  "the future is yours to shape.",
  "stay focused on your goals; they are within reach.",
  "a new chapter in your life is about to begin.",
  "you will achieve great things.",
  "your positivity will attract good fortune.",
  "good things come to those who work hard.",
  "an exciting adventure awaits you.",
  "fortune favors the kindhearted.",
  "your dreams will become a reality.",
  "you will find inner peace.",
  "the best is yet to come for you.",
  "your determination will lead to success.",
  "you will find love and happiness.",
  "a bright future lies ahead.",
  "trust in yourself; you know what's best for you.",
  "a new beginning is on the horizon.",
  "you will soon find what you seek.",
  "the universe is guiding you towards greatness.",
  "you are destined for greatness.",
  "a pleasant surprise is in store for you.",
  "success will come to you in unexpected ways.",
  "you are capable of achieving your dreams.",
  "your positive outlook will lead to success.",
  "good fortune is on its way to you.",
  "your journey will lead to fulfillment.",
  "believe in yourself, and anything is possible.",
  "you will overcome any challenges that come your way.",
  "your future is bright and full of possibilities.",
  "a new opportunity will present itself to you soon.",
  "fortune favors the bold.",
  "you will find happiness in the little things.",
  "your kindness will bring you good fortune.",
  "trust in yourself; you know what's best for you.",
  "a positive mindset will lead to success.",
  "good things come to those who persevere.",
  "you will achieve great things in life.",
  "an exciting journey awaits you.",
  "your hard work will pay off in the end.",
  "you are stronger than you think.",
  "love is on its way to you.",
  "the future is bright for you.",
  "you will find joy and fulfillment.",
  "success is within your grasp.",
  "the universe has a plan for you; trust it.",
  "a new chapter in your life is about to begin.",
  "you are destined for greatness.",
  "fortune favors the courageous.",
  "your dreams will soon become a reality.",
  "you will find inner peace and happiness.",
  "a bright future awaits you.",
  "your determination will lead you to success.",
  "you will find love and companionship.",
  "trust in yourself; you know what's best for you.",
  "a new beginning is on the horizon for you.",
  "you will soon achieve your goals.",
  "the universe is guiding you towards greatness.",
  "you are destined for success.",
  "a pleasant surprise is in store for you soon.",
  "success will come to you when you least expect it.",
  "you have the power to make your dreams come true.",
  "your positive attitude will attract good fortune.",
  "good things are headed your way.",
  "your journey will lead to happiness and fulfillment.",
  "believe in yourself, and anything is possible.",
  "you will overcome any obstacles in your path.",
  "your future is bright and full of promise.",
  "an exciting opportunity will present itself to you soon.",
  "fortune favors the brave; trust in yourself.",
  "you will find happiness in unexpected ways.",
  "your kindness will be rewarded.",
  "trust in yourself; you know what's best for you.",
  "a positive outlook will lead you to success.",
  "good things come to those who work hard and persevere.",
  "you will achieve greatness in life.",
  "an exciting adventure awaits you.",
  "your hard work will pay off in the end.",
  "you are stronger and more capable than you realize.",
  "love is on its way to you; keep your heart open.",
  "the future holds great promise for you.",
  "you will find joy and fulfillment in the days ahead.",
  "success is within your reach; keep pushing forward.",
  "trust in the universe's plan for you.",
  "a new chapter in your life is about to begin.",
  "you are destined for success and happiness.",
  "fortune favors the bold; take risks and trust yourself.",
  "your dreams will soon become a reality.",
  "inner peace and happiness are within your grasp.",
  "a bright and promising future awaits you.",
  "your determination will lead you to great success.",
  "love and companionship are on their way to you.",
  "trust in yourself; you know what's best for you.",
  "a new beginning is just around the corner.",
  "you will soon achieve your goals and dreams.",
  "the universe is guiding you towards greatness.",
  "success is within your reach; keep believing in yourself.",
  "a pleasant surprise awaits you in the near future.",
  "good fortune will come to you when you least expect it.",
  "you have the power to make your dreams a reality.",
  "your positive attitude will attract abundance and success.",
  "good things are coming your way.",
  "your journey will lead you to happiness and fulfillment.",
  "believe in yourself, and you will overcome any obstacles.",
  "your future is bright and full of promise.",
  "an exciting opportunity is on the horizon.",
  "fortune favors the bold"]
